  10_Adding_the_essential_elements_in_Laravel_to_start_charging_with_Stripe[m
  12_Handling_Strong_Customer_Authentication_SCA_with_Stripe_and_Laravel[m
* [32m13_Preparing_a_Subscription_System_for_the_Project[m
  3_preparing_some_visual_components_in_laravel_to_process_payments[m
  5_Allowing_to_consume_the_API_of_any_payment_platform_from_laravel[m
  6_preparing_laravel_to_use_PayPal_as_a_payment_platform[m
  7_implementing_the_necessary_actions_in_laravel_to_use_the_PayPal_api[m
  8_Improving_and_preparing_Laravel_to_use_any_other_payment_platform[m
  implementing_the_necessary_actions_in_laravel_to_use_the_PayPal_api[m
  main[m
  remove[m
